### ISSUE TITLE
Bump to v2.0.0?

### ISSUE THREAD

**Issue by Shimokuni** [lostisland/faraday-em_http#8]
@olleolleolle 

Thank you for the review & merge of #7.
I think it is time to bump major version.
Will the maintainers this repository carry out the upgrade work?
Is there anything I can do to help?

**Comment by olleolleolle** [comment]
@Shimokuni We value your effort and care in making this gem better!

Since you are an active user & committer, already, would you be interested in… maintaining this gem?

**Comment by olleolleolle** [comment]
Also: I can support you in releasing this version, helping you with anything related to that.

**Comment by Shimokuni** [comment]
> Since you are an active user & committer, already, would you be interested in… maintaining this gem?

I am sorry, but my day job is keeping me very busy right now and I am unable to find the time.
If I find any issues, I will of course create an issue or pull request.
But, it does not look like I will be able to get time as a maintainer.

**Comment by olleolleolle** [comment]
The new release is visible at. https://github.com/lostisland/faraday-em_http/releases/tag/v2.0.0

**Comment by Shimokuni** [comment]
Thank you!
